# @package _global_
dataset_repo_id: alanchenly/aloha-transfercube-single-cam

fps: 25
eval:
  # `use_async_envs` specifies whether to use asynchronous environments (multiprocessing).
  # set it to false to avoid some problems of the aloha env
  use_async_envs: false
env:
  name: aloha
  task: AlohaTransferCube-v0
  state_dim: 14
  action_dim: 14
  fps: ${fps}
  episode_length: 400
  gym:
    obs_type: pixels_agent_pos
    render_mode: rgb_array
